### ISSUE TITLE
Front-end overhaul issues

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events#34]
- [x] Three location lines (name, details, address) are not lined up
![image](https://cloud.githubusercontent.com/assets/1965565/24479967/e6c231be-14af-11e7-9aae-528dbde5b267.png)

- [x] `.notification_message` class is broken: https://github.com/BallStateCBER/muncie_events/commit/d9941bcdc4788290a83e478318f6d17d8670a22f#commitcomment-21313498
![image](https://cloud.githubusercontent.com/assets/1965565/24480106/a393d90a-14b0-11e7-87af-286f85839117.png)

- [x] Event details have been moved: https://github.com/BallStateCBER/muncie_events/commit/c733a431fd7f62d165a69e738f4eb88d2a9cf468#commitcomment-21375061
![image](https://cloud.githubusercontent.com/assets/1965565/24480115/ae6027bc-14b0-11e7-9882-8d249a86fbf2.png)

- [x] Buttons have been moved from beside inputs to underneath them, 'add address' needs to stay next to the 'location name' input
![image](https://cloud.githubusercontent.com/assets/1965565/24480028/4a2d90ae-14b0-11e7-80a8-bf85a6eca08d.png)

- [x] Apply Bootstrap styling and responsive design to Customize Event Feed Widget page (/widgets/customize/feed)

- [x] Apply Bootstrap styling and responsive design to Monthly Calendar Widget page (/widgets/customize/month)

- [x] Apply Bootstrap styling and responsive design to Change Password page (/users/change_pass)

Please check these off as they're corrected.

**Comment by ericadeefox** [comment]
Is it OK if the location lines are all three visible/not collapsible? Apparently in Bootstrap 4 it's no longer possible for one data-toggle to have multiple targets. If not that's OK, I can just bring back some js that I thought would be made redundant by Bootstrap.js.

**Comment by PhantomWatson** [comment]
Nah, the intention isn't to do any redesign work like that in this phase. Keep the "what's visible / toggled" designations the same for now.

I think Bootstrap 4 accepts a CSS selector for `data-target`, so it shouldn't have any trouble selecting multiple elements if it's by class name, data attribute, etc.

**Comment by ericadeefox** [comment]
https://github.com/twbs/bootstrap/issues/19813

"I feel like this is an edge case we don't want to explicitly support."--mdo

Which is heartbreaking. Not sure why they stopped supporting multiple data-targets in 4. Either way this means that the JS I removed earlier isn't actually redundant.

**Comment by PhantomWatson** [comment]
Huh. [The docs](collapse) say 

> "**if** your control element is targeting **a single collapsible element** – i.e. the data-target attribute is pointing to an id selector..."

 which implies that the target _could_ be multiple elements. I guess their docs need to catch up to their (lack of) features.

**Comment by PhantomWatson** [comment]
Re-opening and un-checking the location info item. The `location_details` and `address` lines aren't visible in b554099:
![image](https://cloud.githubusercontent.com/assets/1965565/24515539/f06e73a8-1545-11e7-804e-e65ebba8d342.png)

**Comment by PhantomWatson** [comment]
Un-checking the notification-message item. Styling is still missing in b554099:
![image](https://cloud.githubusercontent.com/assets/1965565/24515629/2cb131fc-1546-11e7-98a4-d10b7e25e911.png)

**Comment by PhantomWatson** [comment]
Un-checking the 'add address' button item. Button has been moved in b554099 to be next to a different input:
![image](https://cloud.githubusercontent.com/assets/1965565/24515753/87eb6182-1546-11e7-8607-084003a58157.png)

**Comment by ericadeefox** [comment]
Checked off the original four issues. When I re-cloned the repo and reset git I saw that there were missing changes that had just never been committed or had been otherwise lost? Either way, git should now _definitely_ reflect what I've got locally and I'm doing everything by command line so that this sort of VC confusion doesn't happen again.
