### ISSUE TITLE
Front-end overhaul issues, vol. 3

### ISSUE THREAD

**Issue by PhantomWatson** [BallStateCBER/muncie_events#38]
Here's some new stuff from me, some new stuff from Victoria, and some old stuff from vol. 2 that wasn't taken care of:
- [x] Instead of using `.btn-sm` for buttons, regular-sized buttons are recommended so users have a full-sized target for clicking. (`.btn-sm` still in use in around 10 files)

- [x] The text-alignment of `ul.event_accordion .actions` was changed from right to center

- [x] Some buttons are missing any of [the button type classes listed here](https://getbootstrap.com/docs/3.3/css/#buttons-options), resulting in them not having any borders or `:hover` styles. `.btn-default` is recommended if the situation doesn't call specifically for one of the other button types.

- [x] On medium screen widths, there's not enough room in `#sidebar > .categories` for everything to fit on one line. I recommend either increasing the minimum width or making the icons disappear at smaller widths.
![image](https://user-images.githubusercontent.com/1965565/29722569-63375c0c-898f-11e7-9459-04e815ce4071.png)

- [x] On screen widths from 785-1,007, search input field overlaps link
![image](https://user-images.githubusercontent.com/1965565/29721884-aeada87e-898c-11e7-94d7-d06ffe285ad2.png)

**Comment by ericadeefox** [comment]
So, somehow, in the process of committing these changes, I overwrote the development branch. I have no idea how I did that, I was trying to pull the divide-by-zero commit and it, um, evidently did not do that. I did, however, re-add the divide-by-zero stuff on both this and the 3.x version of ME. Also all these front-end changes I made I also made to the 3.x version.

**Comment by PhantomWatson** [comment]
It shows that [this commit](https://github.com/BallStateCBER/muncie_events/commit/c773abb7939d3cf233ff900db3d96ff9585e39b1) was a new starting commit for the whole repo. It looks like you deleted and restarted the repo locally, then pushed the new version. I'll work on fixing this, but a fix might discard your new commits. If that happens, you can use these for reference when you're re-adding those changes:
- Remove btn-sm classes from buttons: c773abb7939d3cf233ff900db3d96ff9585e39b1
- Align .actions elements to the right: 09fb140f7f77750b235f7260c51d4e13992cef6c
- Add twbs btn classes to buttons: 2b52d7086c90dc4a1579f94038ec3d8d42748d0c
- Add new col-md & col-lg classes to expand sidebar: 89c54bc30ae31914490a6007115c73b5cb8381a5
- Remove -20px top margin from search bar: 7a2eba258cd135ddc672bedbc59386266e8c9d7f

**Comment by PhantomWatson** [comment]
I've unchecked the items that aren't fixed in the latest commit (389d6fe75f610e8d500d6ef1a08f4e31e33b4803) of the fixed development branch, due to your commits getting rolled back.

**Comment by ericadeefox** [comment]
That's fine. I will figure out what happened and re-add the changes...

**Comment by ericadeefox** [comment]
All commits re-added. I never did figure out why the first commit overwrote the whole branch. But it's fine now.
